-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 11:12:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usu_id` INT NOT NULL,
  `usu_nome` VARCHAR(200) NOT NULL,
  `usu_tel.` VARCHAR(45) NULL,
  `alu_email` VARCHAR(200) NOT NULL,
  `usu_matricula` INT NOT NULL,
  `usu_cpf` VARCHAR(45) NOT NULL,
  `usu_situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5
COMMENT = 'Nessa tabela se encontrará os dados do aluno que se cadastrou no site.';


-- -----------------------------------------------------
-- Table `mydb`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modulo` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modulo` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questao` (
  `que_id` INT NOT NULL,
  `que_posicao` INT NULL,
  `que_titulo` VARCHAR(45) NULL,
  `que_pdf` VARCHAR(255) NULL,
  `que_link_video` VARCHAR(200) NULL,
  `modulo_mod_id` INT NOT NULL,
  PRIMARY KEY (`que_id`, `modulo_mod_id`),
  INDEX `fk_questao_modulo1_idx` (`modulo_mod_id` ASC) VISIBLE,
  CONSTRAINT `fk_questao_modulo1`
    FOREIGN KEY (`modulo_mod_id`)
    REFERENCES `mydb`.`modulo` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `tur_id` INT NOT NULL,
  `tur_titulo` VARCHAR(45) NOT NULL,
  `tur_descricao` TEXT NULL,
  PRIMARY KEY (`tur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_has_usuario` (
  `turma_tur_id` INT NOT NULL,
  `usuario_usu_id` INT NOT NULL,
  PRIMARY KEY (`turma_tur_id`, `usuario_usu_id`),
  INDEX `fk_turma_has_usuario_usuario1_idx` (`usuario_usu_id` ASC) VISIBLE,
  INDEX `fk_turma_has_usuario_turma1_idx` (`turma_tur_id` ASC) VISIBLE,
  CONSTRAINT `fk_turma_has_usuario_turma1`
    FOREIGN KEY (`turma_tur_id`)
    REFERENCES `mydb`.`turma` (`tur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_usuario_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `mydb`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modulo_has_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modulo_has_turma` (
  `modulo_mod_id` INT NOT NULL,
  `turma_tur_id` INT NOT NULL,
  PRIMARY KEY (`modulo_mod_id`, `turma_tur_id`),
  INDEX `fk_modulo_has_turma_turma1_idx` (`turma_tur_id` ASC) VISIBLE,
  INDEX `fk_modulo_has_turma_modulo1_idx` (`modulo_mod_id` ASC) VISIBLE,
  CONSTRAINT `fk_modulo_has_turma_modulo1`
    FOREIGN KEY (`modulo_mod_id`)
    REFERENCES `mydb`.`modulo` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulo_has_turma_turma1`
    FOREIGN KEY (`turma_tur_id`)
    REFERENCES `mydb`.`turma` (`tur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
